SELECT
    ID,
    USER_ACCOUNT,
    USER_NAME,
    LANGUAGE,
    EMAIL,
    USER_GROUP,
    USER_JOBSYSTEM,
    WF_AUTHORITY,
    CASE
        WHEN ID_DELETE_DATE IS NULL THEN
            TO_NUMBER('0')
        ELSE
            TO_NUMBER('1')
    END AS DELETE_CHECK,
    ID_DELETE_DATE,
    TO_NUMBER(NVL(RESPONSIBLE_MODEL_SH, 0)) AS RESPONSIBLE_MODEL_SH,
    TO_NUMBER(NVL(RESPONSIBLE_MODEL_AF, 0)) AS RESPONSIBLE_MODEL_AF
FROM
    MST_USER
WHERE
    ID = %(ID)s