SELECT
    MOUR.DISPLAY_SEQ,
    MOUR.ORG_ID,
    MO.ORG_CODE,
    MO.ORG_NAME,
    TO_CHAR(MOUR.EFFECTIVE_START_DATE, 'yyyy-MM-dd') as EFFECTIVE_START_DATE,
    TO_CHAR(MOUR.EFFECTIVE_END_DATE, 'yyyy-MM-dd') as EFFECTIVE_END_DATE,
    CASE
        WHEN MOUR.EMAIL_SEND_FLAG = 0 THEN
            TO_NUMBER('1')
        ELSE
            TO_NUMBER('0')
    END EMAIL_SEND_FLAG
FROM
    MST_ORG_USER_RELATION   MOUR
    LEFT JOIN MST_ORGANIZATION        MO ON MOUR.ORG_ID = MO.ID
WHERE
    MOUR.USER_ID = %(ID)s

ORDER BY MOUR.DISPLAY_SEQ